version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/node:16.17.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.17
      - run: 
          name: Build concurrent images
          command: |
            docker-compose -f docker-compose-build.yaml build --parallel
      - run: 
          name: Displaying Images Built
          command: |
            docker images
      - run:
          name: Tag images
          command: |
            docker tag udagram-api-user tyronmbi/udagram-api-user:v2
            docker tag udagram-api-feed tyronmbi/udagram-api-feed:v2
            docker tag udagram-frontend:local tyronmbi/udagram-frontend:v2
            docker tag reverseproxy tyronmbi/reverseproxy:v2
      - run:
          name: Connect to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push images to DockerHub
          command: |
            docker push tyronmbi/udagram-api-user:v2
            docker push tyronmbi/udagram-api-feed:v2
            docker push tyronmbi/udagram-frontend:v2
            docker push tyronmbi/reverseproxy:v2
  test:
    docker:
      - image: cimg/node:16.17.0
        auth:
          username: tyronmbi
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: |
          echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
